export const NOTIFICATIONS_DETAILS_REQUEST = "NOTIFICATIONS_DETAILS_REQUEST";
export const NOTIFICATIONS_DETAILS_SUCCESS = "NOTIFICATIONS_DETAILS_SUCCESS";
export const NOTIFICATIONS_DETAILS_FAIL = "NOTIFICATIONS_DETAILS_FAIL";

export const NOTIFICATIONS_LIST_REQUEST = "NOTIFICATIONS_LIST_REQUEST";
export const NOTIFICATIONS_LIST_SUCCESS = "NOTIFICATIONS_LIST_SUCCESS";
export const NOTIFICATIONS_LIST_FAIL = "NOTIFICATIONS_LIST_FAIL";
